name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build location service image
      run: docker build /location_service --file Dockerfile --tag location_service:$(date +%s)
#     - name: Build <service name>
#       run: docker build /<service_name> --file Dockerfile --tag <service_name>:$(date +%s)
